title: Mon site
email: ton@email.com
description: >- # courte description
  Mon site personnel généré par Jekyll + minima.
baseurl: "/uioli" # laisser vide pour nom.github.io
url: "https://juanitax.github.io" # remplace nom par ton username
theme: minima
plugins: []
